package report

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/w1r3hound/w1r3hound/internal/core"
)

// GenerateReport writes the final report in JSON, plus a markdown summary.
func GenerateReport(r *core.ReconReport, outputBase string, log *core.Logger) {
	r.Finalize()

	// ── JSON ──
	jsonPath := outputBase + ".json"
	if err := r.SaveJSON(jsonPath); err != nil {
		log.Error("Failed to write JSON report: %v", err)
	} else {
		log.Info("JSON report saved: %s", jsonPath)
	}

	// ── Markdown Summary ──
	mdPath := outputBase + ".md"
	md := generateMarkdown(r)
	if err := os.WriteFile(mdPath, []byte(md), 0600); err != nil {
		log.Error("Failed to write Markdown report: %v", err)
	} else {
		log.Info("Markdown report saved: %s", mdPath)
	}

	// ── Console Summary ──
	printSummary(r, log)
}

// mdInline neutralises untrusted text before it is placed into the hand-built
// Markdown report. Finding titles/descriptions and the target carry
// server-controlled values (Server header, TLS cert CN, cookie names, redirect
// targets, page titles, meta tags). Without escaping, a target can inject
// headings, break the summary table, or — worst — embed a remote image/link
// that fires when the analyst opens the report (SSRF / tracking pixel /
// deanonymisation). The JSON report is safe because json.Marshal escapes; this
// Markdown is assembled by hand, so it must escape here.
func mdInline(s string) string {
	// A finding title/description is single-line: fold line breaks so injected
	// "\n## Heading" or table rows cannot alter the document structure.
	s = strings.ReplaceAll(s, "\r", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	// Drop ANSI/other control bytes.
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		if r == 0x1b || r < 0x20 || (r >= 0x7f && r <= 0x9f) {
			continue
		}
		b.WriteRune(r)
	}
	// Escape the Markdown metacharacters that let text break out of an inline
	// context (code spans, links, images, emphasis, tables, headings).
	return mdEscaper.Replace(b.String())
}

var mdEscaper = strings.NewReplacer(
	"\\", "\\\\",
	"`", "\\`",
	"*", "\\*",
	"_", "\\_",
	"[", "\\[",
	"]", "\\]",
	"(", "\\(",
	")", "\\)",
	"|", "\\|",
	"<", "&lt;",
	">", "&gt;",
	"#", "\\#",
	"!", "\\!",
)

func generateMarkdown(r *core.ReconReport) string {
	var sb strings.Builder

	sb.WriteString("# w1r3hound — System Profile Report\n\n")
	sb.WriteString("> *\"Quiet on the wire. Loud in the data.\"*\n\n")
	sb.WriteString(fmt.Sprintf("**Target:** `%s`\n\n", mdInline(r.Target)))
	sb.WriteString(fmt.Sprintf("**Scan initiated:** %s\n\n", r.StartedAt))
	sb.WriteString(fmt.Sprintf("**Scan completed:** %s\n\n", r.EndedAt))

	// Calculate duration
	startT, _ := time.Parse(time.RFC3339, r.StartedAt)
	endT, _ := time.Parse(time.RFC3339, r.EndedAt)
	duration := endT.Sub(startT).Round(time.Second)
	sb.WriteString(fmt.Sprintf("**Duration:** %s\n\n", duration))

	// Count by severity
	counts := map[core.Severity]int{}
	for _, f := range r.Findings {
		counts[f.Severity]++
	}

	sb.WriteString("## Summary\n\n")
	sb.WriteString("| Severity | Count |\n|----------|-------|\n")
	for _, sev := range []core.Severity{core.SevCritical, core.SevHigh, core.SevMedium, core.SevLow, core.SevInfo} {
		if counts[sev] > 0 {
			sb.WriteString(fmt.Sprintf("| %s | %d |\n", sev, counts[sev]))
		}
	}
	sb.WriteString("\n")

	// Group by WSTG ID
	sb.WriteString("## Findings\n\n")
	for _, sev := range []core.Severity{core.SevCritical, core.SevHigh, core.SevMedium, core.SevLow, core.SevInfo} {
		printed := false
		for _, f := range r.Findings {
			if f.Severity != sev {
				continue
			}
			if !printed {
				sb.WriteString(fmt.Sprintf("### %s\n\n", sev))
				printed = true
			}
			wstg := f.WSTG
			if wstg == "" {
				wstg = "N/A"
			}
			sb.WriteString(fmt.Sprintf("- **[%s]** `%s` — %s\n", sev, mdInline(wstg), mdInline(f.Title)))
			if f.Description != "" {
				sb.WriteString(fmt.Sprintf("  - %s\n", mdInline(f.Description)))
			}
			if f.Data != nil {
				switch d := f.Data.(type) {
				case []string:
					if len(d) > 0 && len(d) <= 20 {
						for _, item := range d {
							sb.WriteString(fmt.Sprintf("    - `%s`\n", mdInline(item)))
						}
					} else if len(d) > 20 {
						for _, item := range d[:20] {
							sb.WriteString(fmt.Sprintf("    - `%s`\n", mdInline(item)))
						}
						sb.WriteString(fmt.Sprintf("    - *...and %d more*\n", len(d)-20))
					}
				case map[string]string:
					for k, v := range d {
						sb.WriteString(fmt.Sprintf("    - **%s**: `%s`\n", mdInline(k), mdInline(v)))
					}
				}
			}
		}
		if printed {
			sb.WriteString("\n")
		}
	}

	sb.WriteString("---\n\n")
	sb.WriteString("*Generated by [w1r3hound](https://github.com/w1r3hound/w1r3hound) — wiretap-grade offensive recon*\n")

	return sb.String()
}

func printSummary(r *core.ReconReport, log *core.Logger) {
	fmt.Fprintf(os.Stderr, "\n")
	log.Module("w1r3hound BREACH REPORT // Summary")

	counts := map[core.Severity]int{}
	for _, f := range r.Findings {
		counts[f.Severity]++
	}

	startT, _ := time.Parse(time.RFC3339, r.StartedAt)
	endT, _ := time.Parse(time.RFC3339, r.EndedAt)
	duration := endT.Sub(startT).Round(time.Second)

	log.Info("Target:   %s", r.Target)
	log.Info("Duration: %s", duration)
	log.Info("Findings: %d total", len(r.Findings))

	for _, sev := range []core.Severity{core.SevCritical, core.SevHigh, core.SevMedium, core.SevLow, core.SevInfo} {
		if counts[sev] > 0 {
			log.Finding(sev, fmt.Sprintf("%d findings", counts[sev]))
		}
	}

	// Print top findings
	fmt.Fprintf(os.Stderr, "\n")
	for _, f := range r.Findings {
		if f.Severity == core.SevCritical || f.Severity == core.SevHigh {
			log.Finding(f.Severity, f.Title)
		}
	}
}
